### ISSUE TITLE
Repo name is not specific

### ISSUE THREAD

**Issue by jnnr** [oemof-heat/workshop#5]
The name is very general. A better name would be like

renewable-village-game,
energy-transition-workshop,
energy-system-planning-game.

Maybe you got even better and more fitting ideas. Anyway, it would help to tell more about what to expect here already in the name. What do you think @jakob-wo, @FranziPl @c-moeller ?

**Comment by jakob-wo** [comment]
I agree with you, the current name is too general.
In my opinion 'energy-system-planning-game' is a good proposal - it speaks for itself.

**Comment by jakob-wo** [comment]
After a few seconds of reconsidering my reply I would like to propose another name, a fusion of your proposals, @jnnr:
'energy-system-planning-workshop' 

Workshop seems to be more appropiate for the content of the repo.

**Comment by jnnr** [comment]
Renamed.
